name: translation_app
description: Demo translation app for SUPERNOVA

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^6.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  hive: ^2.0.2
  http: ^0.13.1
  dartz: ^0.10.0-nullsafety.1
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  flutter_oss_licenses: ^1.0.1
  mockito: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# run 'flutter pub run flutter_launcher_icons:main' to update the icon
flutter_icons:
  image_path: "images/icon.jpg" 
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/


